
-- 1. Hapus tabel lama agar struktur bersih (Reset)
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

-- 2. Buat Tabel Orders (ID TEXT untuk format 'FT-xxxx')
CREATE TABLE orders (
    id TEXT PRIMARY KEY,
    customer_name TEXT,
    order_type TEXT,
    table_number TEXT,
    event_date TEXT,
    status TEXT DEFAULT 'PENDING',
    payment_method TEXT,
    total NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Buat Tabel Order Items dengan RELASI (Foreign Key)
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT REFERENCES orders(id) ON DELETE CASCADE,
    menu_id TEXT,
    name_at_time TEXT,
    price_at_time NUMERIC,
    quantity INTEGER,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Mengaktifkan Row Level Security
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- 5. Kebijakan Akses (RLS Policies)
CREATE POLICY "Enable all access for orders" ON orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for order_items" ON order_items FOR ALL USING (true) WITH CHECK (true);
